# Generated by Django 4.2 on 2025-12-03 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('TEXT', 'text'), ('MCQ', 'mcq'), ('NUM', 'number'), ('BOOL', 'bool')], max_length=10)),
                ('validation_rules', models.JSONField(default=dict)),
                ('risk_weight', models.PositiveSmallIntegerField(default=1)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='banks.bank')),
            ],
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['bank', 'category', 'version'], name='questionnai_bank_id_1c637b_idx'),
        ),
    ]
